version: "3.8"

services:
  api:
    build: .
    ports:
      - "7999:7999"
    volumes:
      - .:/usr/src/app
    environment:
      - DEBUG=1
      - PYTHONPATH=.
      - PYTHONUNBUFFERED=1
      - BETTER_EXCEPTIONS=1
      - DATABASE_URL=postgresql://postgres:postgres@db/postgres
    depends_on:
      - db
    command: ["./start.sh"]

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
# volumes:
#   postgres_data:
