name: Code Quality
on: [push, pull_request]
env:
  PYTHON_VERSION: 3.11
  POETRY_VERSION: 1.5.1
jobs:
  py-code-quality:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Install Poetry
      run: |
        pipx install poetry==${{ env.POETRY_VERSION }}
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: poetry
        cache-dependency-path: poetry.lock
    - name: Setup dependencies
      run: |
        poetry install --no-root
    - name: Lint with Ruff
      run: |
        poetry run ruff app
    - name: Lint with black
      run: |
        poetry run black app --check
    - name: Typecheck with pyright
      run: |
        poetry run pyright app
    - name: Test with pytest
      run: |
        export PYTHONPATH='.'
        poetry run pytest app
